packages:
  - "apps/*"
  - "packages/*"
  - "examples/*"

allowBuilds:
  esbuild: true
  unrs-resolver: true
  webgpu: true

patchedDependencies:
  "@babylonjs/core@9.17.0": patches/@babylonjs__core@9.17.0.patch
  "@sparkjsdev/spark@2.1.0": patches/@sparkjsdev__spark@2.1.0.patch
